// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { Player, PlayerTableId } from "./tables/Player.sol";
import { LandConfig, LandConfigTableId } from "./tables/LandConfig.sol";
